#!/usr/bin/env python3
"""Attach an ``infra_pr`` block to each ``matched`` obligation.

Glue between the detector (Phase 1), the generator, and the publisher: for every
matched obligation it generates the infra files, computes the branch + deep-link,
and (in dry_run) stages without pushing. human_gated / blocked obligations are
left untouched — there is nothing safe to stage.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Callable

from generate_infra_change import generate_files
from publish_infra_pr import branch_name, compare_url, stage_branch, _default_runner


def stage_obligations(
    obligations: list[dict[str, Any]],
    repo: str,
    base: str,
    allow: list[str],
    templates_root: str | Path,
    source_pr: str,
    dry_run: bool = True,
    runner: Callable[[list[str]], str] = _default_runner,
) -> list[dict[str, Any]]:
    out: list[dict[str, Any]] = []
    for ob in obligations:
        ob = dict(ob)
        if ob.get("outcome") == "matched":
            pack = ob.get("pack") or {}
            files = generate_files(pack, ob.get("inputs") or {}, templates_root, allow)
            branch = branch_name(ob["type"], ob.get("inputs") or {})
            approver = pack.get("approver") or ""
            title = f"MergeProof: {ob['type']} for {(ob.get('inputs') or {}).get('service', 'service')}"
            body = (
                f"Generated by MergeProof for {source_pr}\n\n"
                f"Approver: {approver}\n"
                f"Generated files:\n" + "\n".join(f"- {p}" for p in sorted(files))
            )
            staged = stage_branch(repo, base, branch, files, title, dry_run=dry_run, runner=runner)
            staged["create_url"] = compare_url(repo, base, branch, title, body)
            staged["diff"] = files
            ob["infra_pr"] = staged
        out.append(ob)
    return out
